### ISSUE TITLE
Install failed on Mac OS X El Capitan

### ISSUE THREAD

**Issue by SimplicityGuy** [ssagar0/zoom#4]
```
  Downloading zoom-0.0.13b2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-_tqTJ2/zoom/setup.py", line 2, in <module>
        from zoom.__version__ import __version__
      File "zoom/__init__.py", line 1, in <module>
        import zoom_client
      File "zoom/zoom_client.py", line 3, in <module>
        import click
    ImportError: No module named click
```

After running `sudo pip install zoom`.

**Comment by SimplicityGuy** [comment]
Hmm, looks like `setup.py` has the `install_requires` parameter already.

And pip installing click, and then pip installing zoom works fine.

**Comment by ssagar0** [comment]
This should work now. Distributing as a wheel.
